---
- name: create .kube directories in user's home
  file:
    path: "/home/ubuntu/.kube"
    state: absent

- name: create .kube directories in user's home
  file:
    path: "/home/ubuntu/.kube"
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode: 0755

- name: slurp admin kubeconfig
  slurp:
    src: /etc/kubernetes/admin.conf
  register: kubeconfig
  delegate_to: "{{ groups['master'][0] }}"

- name: setup the kubeconfig
  copy:
    remote_src: True
    content: "{{ kubeconfig.content }}"
    dest: "/home/ubuntu/.kube/config"
    owner: "ubuntu"
    group: "ubuntu"
    mode: 0600
    no_log: True

- name: configure bash completion
  lineinfile:
    path: "/home/ubuntu/.bashrc"
    line: "source <(kubectl completion bash)"