---
- name: add docker apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower}}/gpg"
    id: 0EBFCD88
  register: apt_key_result
  until: apt_key_result is success
  retries: 5
  delay: 5

- name: add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower}} {{ ansible_distribution_release|lower }} stable"
    update_cache: true
  register: apt_repository_result
  until: apt_repository_result is success
  retries: 5
  delay: 5

- name: install docker
  apt:
    name: "docker-ce={{ docker_version }}"
    update_cache: True
    cache_valid_time: 60
    state: present
  register: apt_result
  until: apt_result is success
  retries: 5
  delay: 5

- name: create docker directory
  file:
    dest: /etc/docker
    state: directory

- name: configure the docker daemon
  template:
    dest: /etc/docker/daemon.json
    src: etc/docker/daemon.json
  notify:
    - restart docker

- meta: flush_handlers

- name: create a service.d directory for config
  file:
    dest: /etc/systemd/system/docker.service.d
    state: directory

