---
- hosts: bastion
  become: yes
  roles:
    - common
    - docker
    - kubernetes
    
- hosts: etcd
  become: yes
  roles:
    - common
    - docker
    - kubernetes
    - etcd

- hosts: master
  become: yes
  roles:
    - common
    - docker
    - kubernetes
    - kubernetes-master

- hosts: node
  become: yes
  roles:
    - common
    - docker
    - kubernetes
    - kubernetes-node

- hosts: bastion
  become: yes
  roles:
    - kubernetes-user